### ISSUE TITLE
50% through batch I get this error.

### ISSUE THREAD

**Issue by pinballelectronica** [mantasu/face-crop-plus#1]
image = cv2.cvtColor(cv2.imread(path), cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'

cli argument: (windows)

face-crop-plus -i I:\AI\imgtmp\_1024x768\sharpened\AI\1024\_1024x768 --output-size 512 512 -d cuda:0 -b 5 --face-factor 0.75 -o  I:\AI\imgtmp\_1024x768\sharpened\AI\1024\_1024x768\faces

4090 cuda 12.1

Wondering if it broke on a 0 byte file it tried to parse or a broken image?

**Comment by mantasu** [comment]
Yeah, I experienced that too, if the image is corrupted/unreadable, it will give this error. Will fix it in the next release to raise a warning instead.

**Comment by pinballelectronica** [comment]
I'll pull that- thanks!   I ran this through 5K images and about 10% of them have this very trippy Kaleidoscope look- heads coming out of heads and multiple eyes and sometimes just a literal kaleidoscope where I cannot even make out the image- is this something I can remedy or tune out?  

Thank you, love this tool!

**Comment by mantasu** [comment]
Haha, it's because the default `padding` is set to _"reflect"_. Try changing to _"replicate"_: `--padding replicate`

**Comment by pinballelectronica** [comment]
in other words, rtfm.  lol.  thanks!

**Comment by pinballelectronica** [comment]
also great pipeline through captionr for computer vision'y things

**Comment by mantasu** [comment]
Thanks, yeah the aim is to help with the preprocessing mess that can happen

**Comment by mantasu** [comment]
True I can imagine, and quality enhancement would triple that! Hopefully we can expect more efficient models in the future 😂
